### ISSUE TITLE
ISOBMFF container format support

### ISSUE THREAD

**Issue by fdelapena** [gianni-rosato/aviator#33]
tl;dr: Besides MKV and WebM, support .mp4 container (afaik not affected by patents itself).
Pretty usual out there and widely supported for AV1-based players.
Selected codecs support being encapsulated on it as specifications show:
ISOBMFF: https://www.w3.org/TR/mse-byte-stream-format-isobmff/
AV1: https://aomediacodec.github.io/av1-isobmff/v1.2.0.html
Opus: https://opus-codec.org/docs/opus_in_isobmff.html
ffmpeg used here likely supports this container already for them.

**Comment by gianni-rosato** [comment]
Hi,
Thank you for your suggestion. While FFmpeg does support MP4, I'm currently against supporting MP4 because of its nature as a proprietary container & my personal interest in keeping Aviator a proponent for the accessibility of open source media standards. MKV is universal & can handle basically any video/audio/subtitle stream, while WebM is more limited but works for our needs & is great for web compatibility.

If you'd like to take Aviator's output & convert it to MP4, you can run `ffmpeg -i input.mkv -c copy out.mp4` or the same for a WebM input. This may not work if the video contains subtitles. Thank you for your feedback, & I hope you continue to enjoy Aviator!
