### ISSUE TITLE
Improve app icon

### ISSUE THREAD

**Issue by jimmac** [gianni-rosato/aviator#36]
Aviator looks like a cool video processor/encoder. I do like the fun spin on AV1 in the name. To feature it as a GNOME Circle app, it would be nice to polish the app icon.

**Comment by jimmac** [comment]
Perhaps the last one is too complex to work as an app icon, but could be a base for the initial state illustration.

**Comment by gianni-rosato** [comment]
Hi! Are you representing GNOME Circle here? I haven't seen any activity on my GNOME Gitlab issue since I filed it.

**Comment by jimmac** [comment]
No, just wanting to help with the icon design execution. Accepting my contributions have no impact on the process.

**Comment by jimmac** [comment]
![image](https://user-images.githubusercontent.com/14821/227524898-570d1834-b79f-4359-beb2-e8e26b00e963.png)

**Comment by gianni-rosato** [comment]
That certainly looks nice! I'd be happy to take an Inkscape SVG to tinker with on my own. In the meantime, I'd like to stick with my current icon until my GNOME circle application is officially reviewed, as it represents the app in a way that I find pleasing & is relatively entrenched as the app's symbol (as far as I can glean from those using it who I've talked to)

**Comment by jimmac** [comment]
I think you're confusing me with ChatGPT. I respect your desire not to work with me and the specific skillset I'm bringing to the table. If you're looking for assets to reuse on your effort, look at the [Firmware](https://gitlab.gnome.org/World/gnome-firmware/-/tree/master/data/icons) icon I've derived from.

**Comment by gianni-rosato** [comment]
"I think you're confusing me with ChatGPT" doesn't make it sound like you feel any modicum of respect coming from my end. I apologize if that is the case. Icons are very personal, and I happen to like mine very much & I feel proud of it. I genuinely appreciate your efforts, but this is my application & I will not be taking an icon without delivering feedback of my own to your efforts. I hope you understand why.

**Comment by jimmac** [comment]
Feedback is why I created this issue and started with sketches. When you respond with wanting to take the design into your hands, that's not collaboration.

**Comment by gianni-rosato** [comment]
Let's treat it like a PR to change the source code; if I do not agree with the changes proposed in a PR or I would like to see another implementation, I am free to merge the PR and then make my own modifications. If the author of the PR disagrees with these modifications, they are free to voice their concerns to me & I am free to either accept or reject their feedback. Either way, their primary intention is to help improve my application, not to apply their vision of how my app should operate.

If I modify your Inkscape SVG, it is not because I don't respect your work, it is because this is my application & it is my job to alter contributions in order to align them with my vision.

In this case, I recognize your talent & I'd like to send modifications back to you for review if I make any. If you've decided in advance that my input isn't worthwhile, that becomes a two way street.

An icon is my brand, the first thing anyone sees when they look at my application. It is one of the most critical pieces of how the app appears and functions, maybe moreso than some internal design decisions like which AV1 encoder I decide to use. I need to be able to have a say in how my icon comes out, and I would need an SVG for that, or the current icon will remain.

**Comment by shssoichiro** [comment]
@jimmac It feels like you are only trying to contribute because you want recognition for creating the logo, not because you actually want to collaborate and contribute to the project. People do not do open source to see their name in lights on the internet, it's about building something better. If you are not okay with your contributions having future modifications made to them, then I don't think open source is the correct venue you're looking for.

**Comment by jimmac** [comment]
If I was looking for the grand recognition you describe, I'd probably figure out it's not as shiny as it seemed, about 2 decades ago. What is the feedback I got for any of the proposals above? Where is the direction?

**Comment by master-of-zen** [comment]
I felt that this exchange was not dramatic enough, not a single life ruined, so i make chatGPT generate a couple messages. (To say straight, its' a joke)

**Comment by master-of-zen** [comment]
gianni-rosato: You're not getting it, are you? This is my application, my brand, my identity! I will not let you take away my vision and replace it with something that is not aligned with my values. You have no respect for my work, my efforts, and my art! You are just trying to force your own ideas onto me, and I will not tolerate it!

jimmac: Oh, please! You're being so dramatic and over the top! This is not about you or your ego, it's about collaboration and creating something better than what we have now. You're not the only one who cares about this project, you know? We all want it to succeed, and that means being open to feedback and ideas from others. If you're not willing to do that, then maybe you should just do this on your own.

gianni-rosato: How dare you! You have no idea how much time, effort, and passion I have put into this project! And now you come along, thinking you can just waltz in here and tell me what to do? No, I will not stand for it! I will fight tooth and nail to protect my vision and my art, and I will not let you or anyone else take it away from me!

jimmac: Wow, you really are delusional, aren't you? This is not a battle, it's a conversation. We're all on the same team here, trying to make something great. If you can't see that, then maybe you're not the right person for this project. We need people who are willing to work together and listen to each other, not people who are going to throw a tantrum every time someone suggests a change.

**Comment by gianni-rosato** [comment]
😂 Master of Zen himself

**Comment by jimmac** [comment]
> This is not about you or your ego, it's about collaboration and creating something better than what we have now. 

The whole purpose of the issue was to do exactly that. This is how this usually goes -- by providing some concepts that are easily discarded and working with the maintainer -- [eg here](https://gitlab.com/gregorni/asciiimages/-/issues/1) or [here](https://gitlab.gnome.org/feaneron/liveblast/-/issues/18). I made the error not pointing out the issues with the existing icon and not holding off the fullcolor work before getting any sort of direction. But I guess that's pointless at this stage.  I'm not sure how making fun of my effort is going to help your project in any way.

**Comment by gianni-rosato** [comment]
Master of Zen's making fun of me too, it's all in good faith. I wouldn't take it to heart.

In the example of asciiimages, he made a suggestion & u implemented it. Instead of making u do the work, I'd simply make the suggestion through an SVG that I'd send back to you, so you don't have to try and interpret my suggestions through text. I don't want to burden you.

This is all I've been asking for the entire time, it's not that deep. I'd rather give u a visual reference for something I'd like to change instead of just barking at you

**Comment by TriVoxel** [comment]
@jimmac Learn how to take rejection bro! He didn't even tell you it was bad. It's a decent design, but it could probably use some polish and refinement, by no means perfect. Besides, he only acknowledged that he liked the concept, never told you to fire up a design. He just doesn't want to change anything until he feels ready. He's the developer, respect his position, he created and maintains the app. If you've got a problem with it, fork it. Stop complaining, you're just not always going to get your way.
