### ISSUE TITLE
[request] Preset Speed  -1 

### ISSUE THREAD

**Issue by AndreaMonzini** [gianni-rosato/aviator#59]
Hello thank you for the very interesting project !

Could be possible to add the preset speed -1 as "quality reference" introduced with SVT-AV1 1.5.0 ? ( even if with much slower encoding time ).
Maybe adding the alert in the text "Hover" about the super slow encoding time.
I am testing encoding with speed 0 for ultra low bit rates.

Andrea

**Comment by gianni-rosato** [comment]
Very adventurous :) I'm glad people are interested in these painfully slow presets, haha. I've obscured away preset 13 and -1 because they're essentially unusable for separate reasons, but I'll add p-1 back in.

Also, Aviator uses SVT-AV1-PSY under the hood - which features a preset -2 that is like 10x slower than preset -1, if you *really* want to go there. I don't think I'm gonna add that, as it is truly bewilderingly slow for very little benefit if any

**Comment by AndreaMonzini** [comment]
Thank you !
Also very interesting info.
I plan to test also the slowest preset also in libaom and rav1e !

**Comment by gianni-rosato** [comment]
Oh boy, have fun lol. the slow presets take such an incredibly long time.

**Comment by gianni-rosato** [comment]
b8c74c1014c156be6208026451c6fa0dc6347d81

**Comment by AndreaMonzini** [comment]
Hello !

i was testing presets 0, -1 and -2 but i have problems with -2:

source file: 1920x1080    23 seconds 
with presets 0 ( 12 minutes encoding )  and -1 ( 20 minutes encoding ) i have expected results.
but with presets -2 the encoding time is just 50 seconds and with worse compression.

Apparently it is like running with an higher presets instead of -2
Better to open a new issue ?

PS presets -1 is not too slow for me, so i would test presets -2 if possible !

Thank you !
